export const PROBLEM_SIGNALS = [
  "i wish",
  "looking for a tool",
  "looking for a app",
  "looking for an app",
  "is there an app",
  "is there a tool",
  "frustrated with",
  "alternative to",
  "anyone know a tool",
  "does anyone know",
  "need a tool",
  "need an app",
  "wish there was",
  "wish there were",
  "pain point",
  "struggling with",
  "hate using",
  "tired of",
  "manual process",
  "no good solution",
] as const;
